version: '3.8'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - 3306

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    expose: 
      - 9000
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure


  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
  
  redis:
      container_name: redis
      networks:
        - inception
      build:
        context: requirements/bonus/redis
        dockerfile: Dockerfile
      depends_on:
      - wordpress
      env_file: .env
      restart: on-failure
  ftp:
    container_name: ftp
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "21:21"
    restart: on-failure

  static_site:
    build: 
      context: requirements/bonus/static_site
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "8000:8000"
    restart: on-failure

  adminer:
    build: 
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - 8080:80
    restart: on-failure
  
  django:
    build: 
      context: requirements/bonus/django
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "3000:3000"
    restart: on-failure

volumes:
  wordpress: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/khadija/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/khadija/data/mariadb'

networks:
  inception:
    driver: bridge
